# Generated by Django 5.2.3 on 2025-07-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='booking_com_url',
            field=models.URLField(blank=True, help_text='Booking.com listing URL'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='custom_domain',
            field=models.CharField(blank=True, help_text='Custom domain for microsite (e.g., myhotel.com)', max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='microsite_enabled',
            field=models.BooleanField(default=True, help_text='Enable microsite for this property'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='microsite_primary_color',
            field=models.CharField(default='#3B82F6', help_text='Primary brand color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='hotel',
            name='microsite_secondary_color',
            field=models.CharField(default='#1E40AF', help_text='Secondary brand color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='hotel',
            name='microsite_theme',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('luxury', 'Luxury'), ('minimal', 'Minimal'), ('tropical', 'Tropical')], default='modern', help_text='Microsite theme/design', max_length=20),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tripadvisor_url',
            field=models.URLField(blank=True, help_text='TripAdvisor listing URL'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter/X profile URL'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube channel URL'),
        ),
    ]
