# Generated by Django 5.2.3 on 2025-07-02 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Room name/number', max_length=200)),
                ('room_type', models.CharField(choices=[('standard', 'Standard Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite'), ('family', 'Family Room'), ('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('king', 'King Room'), ('queen', 'Queen Room'), ('presidential', 'Presidential Suite'), ('penthouse', 'Penthouse'), ('studio', 'Studio Apartment'), ('one_bedroom', '1 Bedroom Apartment'), ('two_bedroom', '2 Bedroom Apartment'), ('three_bedroom', '3 Bedroom Apartment'), ('villa', 'Private Villa'), ('cottage', 'Cottage'), ('cabin', 'Cabin'), ('loft', 'Loft'), ('dormitory', 'Dormitory Bed')], help_text='Type of room', max_length=20)),
                ('description', models.TextField(help_text='Detailed room description')),
                ('short_description', models.CharField(blank=True, help_text='Brief description', max_length=300)),
                ('max_occupancy', models.PositiveIntegerField(help_text='Maximum number of guests')),
                ('adults', models.PositiveIntegerField(default=2, help_text='Number of adults')),
                ('children', models.PositiveIntegerField(default=0, help_text='Number of children')),
                ('infants', models.PositiveIntegerField(default=0, help_text='Number of infants')),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Room size in square meters', max_digits=8, null=True)),
                ('bed_type', models.CharField(choices=[('single', 'Single Bed'), ('double', 'Double Bed'), ('queen', 'Queen Bed'), ('king', 'King Bed'), ('twin', 'Twin Beds'), ('bunk', 'Bunk Bed'), ('sofa', 'Sofa Bed')], help_text='Type of bed', max_length=20)),
                ('number_of_beds', models.PositiveIntegerField(default=1, help_text='Number of beds')),
                ('bathroom_type', models.CharField(choices=[('private', 'Private Bathroom'), ('ensuite', 'En-suite Bathroom'), ('shared', 'Shared Bathroom'), ('half', 'Half Bathroom')], help_text='Bathroom type', max_length=20)),
                ('amenities', models.TextField(blank=True, help_text='Room amenities (comma-separated)')),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=True)),
                ('has_tv', models.BooleanField(default=True)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price per night', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('is_available', models.BooleanField(default=True, help_text='Is room currently available?')),
                ('min_stay', models.PositiveIntegerField(default=1, help_text='Minimum nights required')),
                ('max_stay', models.PositiveIntegerField(blank=True, help_text='Maximum nights allowed', null=True)),
                ('check_in_time', models.TimeField(blank=True, help_text='Room-specific check-in time', null=True)),
                ('check_out_time', models.TimeField(blank=True, help_text='Room-specific check-out time', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['hotel', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date')),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('blocked', 'Blocked'), ('maintenance', 'Under Maintenance')], default='available', max_length=20)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override price for this date', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about availability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room Availability',
                'verbose_name_plural': 'Room Availability',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='RoomFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_percentage', models.BooleanField(default=False)),
                ('is_mandatory', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Room image', upload_to='room_images/')),
                ('caption', models.CharField(blank=True, help_text='Image caption', max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the main image?')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='RoomPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('base', 'Base Price'), ('weekend', 'Weekend Price'), ('holiday', 'Holiday Price'), ('seasonal', 'Seasonal Price'), ('special', 'Special Event Price')], default='base', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per night', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('start_date', models.DateField(blank=True, help_text='Start date for this pricing', null=True)),
                ('end_date', models.DateField(blank=True, help_text='End date for this pricing', null=True)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Room Pricing',
                'verbose_name_plural': 'Room Pricing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_inclusive', models.BooleanField(default=False)),
            ],
        ),
    ]
