# Generated by Django 5.2.3 on 2025-07-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
