# Generated by Django 5.2.3 on 2025-07-03 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rental',
            field=models.ForeignKey(blank=True, help_text='Rental this room belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='rentals.rental'),
        ),
    ]
