# Generated by Django 5.2.3 on 2025-07-02 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(help_text='Unique booking reference', max_length=20, unique=True)),
                ('guest_name', models.CharField(help_text='Primary guest name', max_length=200)),
                ('guest_email', models.EmailField(help_text='Guest email address', max_length=254)),
                ('guest_phone', models.CharField(help_text='Guest phone number', max_length=20)),
                ('guest_address', models.TextField(blank=True, help_text='Guest address')),
                ('guest_id_number', models.CharField(blank=True, help_text='Guest ID/Passport number', max_length=50)),
                ('check_in_date', models.DateField(help_text='Check-in date')),
                ('check_out_date', models.DateField(help_text='Check-out date')),
                ('nights', models.PositiveIntegerField(help_text='Number of nights')),
                ('adults', models.PositiveIntegerField(default=1, help_text='Number of adults')),
                ('children', models.PositiveIntegerField(default=0, help_text='Number of children')),
                ('infants', models.PositiveIntegerField(default=0, help_text='Number of infants')),
                ('room_rate', models.DecimalField(decimal_places=2, help_text='Room rate per night', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before taxes and fees', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount', max_digits=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total fee amount', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount to pay', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('direct', 'Direct Booking'), ('website', 'Website'), ('phone', 'Phone'), ('email', 'Email'), ('walk_in', 'Walk-in'), ('agent', 'Travel Agent'), ('booking_com', 'Booking.com'), ('airbnb', 'Airbnb'), ('expedia', 'Expedia'), ('other', 'Other')], default='direct', max_length=20)),
                ('special_requests', models.TextField(blank=True, help_text='Special requests from guest')),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes (not visible to guest)')),
                ('actual_check_in', models.DateTimeField(blank=True, help_text='Actual check-in time', null=True)),
                ('actual_check_out', models.DateTimeField(blank=True, help_text='Actual check-out time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyRoomPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('mpesa', 'M-Pesa'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('flutterwave', 'Flutterwave'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='External transaction ID', max_length=100)),
                ('reference_number', models.CharField(blank=True, help_text='Payment reference number', max_length=100)),
                ('gateway_response', models.TextField(blank=True, help_text='Payment gateway response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
